#!/bin/bash

Build()
{
ECR_REPO=659428036160.dkr.ecr.ap-south-1.amazonaws.com/nginx
DOCKER_BUILD_TAG=$GIT_BRANCH-${BUILD_NUMBER}
docker build -t $ECR_REPO:$DOCKER_BUILD_TAG --pull=true .
if [ $? -eq 0 ]; then 
echo "Docker build got success"
else 
echo "Docker build was failed"
exit 1
fi
docker images -q $ECR_REPO
GET_LOGIN=$(aws ecr get-login --no-include-email --region ap-south-1)
IMAGE_ID=$(docker images -q $ECR_REPO | awk "NR==1{print $1}")
echo $IMAGE_ID
docker tag $IMAGE_ID $ECR_REPO:latest
docker inspect $IMAGE_ID
echo $GET_LOGIN
$GET_LOGIN
docker push $ECR_REPO:$DOCKER_BUILD_TAG && docker push $ECR_REPO:latest
if [ $? -eq 0 ]; then 
echo "Docker Push got success"
docker logout
else 
echo "Docker Push was failed"
docker logout
exit 1
fi
}
