#!/bin/bash

startDeploy()
{
# Create a new task definition for this build
sed -e "s;GIT_COMMIT;${IMAGE_VERSION};g" ${JSON_FILE}.json > ${JSON_FILE}-new-${BUILD_NUMBER}.json

sed -e "s;GROUP_NAME;${GIT_BRANCH};g" ${JSON_FILE}-new-${BUILD_NUMBER}.json > ${JSON_FILE}-${BUILD_NUMBER}-v1.json
sed -e "s;task_role;${TASK_ROLE};g" ${JSON_FILE}-${BUILD_NUMBER}-v1.json > ${JSON_FILE}-${BUILD_NUMBER}.json
cat ${JSON_FILE}-${BUILD_NUMBER}.json

 
aws ecs register-task-definition --cli-input-json file://$HOME/tasks/fargate-task.json --region ap-south-1

# Jenkins Job wait until service is avaliable in cluster
aws ecs wait services-stable --cluster ${CLUSTER} --services ${SERVICE_NAME} --region ap-south-1 

if [ $? -eq 0 ]; then
echo "Build got deployed successfully"
else
echo "Build failed"
exit 1
fi
rm -rf ${JSON_FILE}-${BUILD_NUMBER}.json
}

if [ "$GIT_BRANCH" == "main" ]
then
SERVICE_NAME="nginx-service"
IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
TASK_FAMILY="nginx-service"
CLUSTER="Nginx-cluster"
JSON_FILE="nginx-service"
RUNNING_COUNT=1
}
